export const LEARNER_LOGIN_PENDING = "LEARNER_LOGIN_PENDING";
export const LEARNER_LOGIN_COMPLETE = "LEARNER_LOGIN_COMPLETE";
export const LEARNER_LOGIN_ERROR = "LEARNER_LOGIN_ERROR";
export const LEARNER_SIGN_UP_PENDING = "LEARNER_SIGN_UP_PENDING";
export const LEARNER_SIGN_UP_COMPLETE = "LEARNER_SIGN_UP_COMPLETE";
export const LEARNER_SIGN_UP_ERROR = "LEARNER_SIGN_UP_ERROR";
export const OTP_PENDING = "OTP_PENDING";
export const OTP_VERIFIED = "OTP_VERIFIED";
export const OTP_ERROR = "OTP_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const SET_JWTTOKEN = "SET_JWTTOKEN";

// instructor naming
export const SET_INSTRUCTOR = "SET_INSTRUCTOR";
export const DELETE_INSTRUCTOR = " DELETE_INSTRUCTOR";

// cart namings
export const SET_CART = "SET_CART";
export const DELETE_CART = " DELETE_CART";

// set billing
export const SET_BILLING = "SET_BILLING";

// booking reduer
export const BOOKING_PENDING = "BOOKING_PENDING";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const BOOKING_FAILED = "BOOKING_FAILED";
export const SET_BOOKING = "SET_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";
export const SET_PICKUP_DETAILS = "SET_PICKUP_DETAILS";
export const DELETE_PICKUP_DETAILS = "DELETE_PICKUP_DETAILS";

// booking reduer
export const PURCHASE_CREDIT_PENDING = "PURCHASE_CREDIT_PENDING";
export const PURCHASE_CREDIT_SUCCESS = "PURCHASE_CREDIT_SUCCESS";
export const PURCHASE_CREDIT_ERROR = "PURCHASE_CREDIT_ERROR";

// view boookings
export const SET_ACTIVE_BOOKING = "SET_ACTIVE_BOOKING";
export const DELETE_ACTIVE_BOOKING = "DELETE_ACTIVE_BOOKING";
