export const LEARNER_LOGIN_PENDING = "LEARNER_LOGIN_PENDING";
export const LEARNER_LOGIN_COMPLETE = "LEARNER_LOGIN_COMPLETE";
export const LEARNER_LOGIN_ERROR = "LEARNER_LOGIN_ERROR";
export const LEARNER_SIGN_UP_PENDING = "LEARNER_SIGN_UP_PENDING";
export const LEARNER_SIGN_UP_COMPLETE = "LEARNER_SIGN_UP_COMPLETE";
export const LEARNER_SIGN_UP_ERROR = "LEARNER_SIGN_UP_ERROR";
export const OTP_PENDING = "OTP_PENDING";
export const OTP_VERIFIED = "OTP_VERIFIED";
export const OTP_ERROR = "OTP_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_JWTTOKEN = "SET_JWTTOKEN";

// instructor naming
export const SET_INSTRUCTOR = "SET_INSTRUCTOR";
export const DELETE_INSTRUCTOR = " DELETE_INSTRUCTOR";
